services:
    nginx:
        image: nginx:1.25-alpine3.18
        container_name: laravel-live-nginx
        restart: unless-stopped
        tty: true

        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /var/www/mariadb
        depends_on:
            - app
            - db
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - laravel-live-network

    app:
        build:
            args:
                user: adityaa
                uid: 1000
                env_file: .env
            context: ./
            dockerfile: Dockerfile
        image: laravel-live-app
        container_name: laravel-live
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - /var/www/mariadb
            - /var/www/redis
            - ./deploy.prod.sh:/deploy.prod.sh

        expose:
            - "9000"
            - "9003"
        networks:
            - laravel-live-network

    db:
        image: mariadb:10.11-jammy
        container_name: laravel-live-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: '%'
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb:/var/lib/mysql
        networks:
            - laravel-live-network



    laravel-live-redis:
        image: redis:latest
        container_name: laravel-live-redis
        restart: unless-stopped
        command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis}"
        tty: true
        depends_on:
            - app
        env_file:
            - .env
        ports:
            - "6379:6379"
        networks:
            - laravel-live-network
        volumes:
            - ./redis:/data
            - /var/www/mariadb
            - /var/www/node_modules

















networks:
    laravel-live-network:
        driver: bridge

